remote_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSKGIZ6wlRWuZ4A2xKa5bfFuHER8k9HlkzjVDRipXTNEHTbmnme0V0CY0eeCowrg6mkzbQKn6q7MSIU/pub?output=csv"
proj_dir: "C:/Users/rburn/Documents/APPS305/WestNileOutbreak/"
data_format: "csv"
geocoder_prefix_url: ""
geocoder_suffix_url: ""
